version: "3.9"

services:
  laravel:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: discord_clone
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  angular:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: angular_app
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "4200:4200"
    stdin_open: true
    tty: true

volumes:
  mysql_data:
